"""add multiple controls

Revision ID: 4a9fc1b3b128
Revises: 20260527_drop_unique_disciplines
Create Date: 2026-06-01 04:49:18.106621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a9fc1b3b128'
down_revision: Union[str, None] = '20260527_drop_unique_disciplines'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('discipline_blocks', sa.Column('has_course_project', sa.Boolean(), nullable=False))
    op.add_column('discipline_blocks', sa.Column('has_rz', sa.Boolean(), nullable=False))
    op.add_column('discipline_blocks', sa.Column('has_rgr', sa.Boolean(), nullable=False))
    op.add_column('discipline_blocks', sa.Column('has_referat', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discipline_blocks', 'has_referat')
    op.drop_column('discipline_blocks', 'has_rgr')
    op.drop_column('discipline_blocks', 'has_rz')
    op.drop_column('discipline_blocks', 'has_course_project')

    # ### end Alembic commands ###
